### ISSUE TITLE
Make precompiled binary for PPC, PPC64, ARM, ARM64, x86

### ISSUE THREAD

**Issue by DmitryHetman** [rainautumn/ttytanks#16]

**Comment by rainautumn** [comment]
ты угараешь? я на arm7 когда билдил -- офигел.

**Comment by DmitryHetman** [comment]
Кросс-компиляцию надо настроить, и если статические бинарники собирать как сейчас то будет все круто, можно будет даже в андроиде запускать с терминала игру, либы внешние ей не нужны.

**Comment by DmitryHetman** [comment]
Sparc, SPARC64 еще, MIPS может там, хотя мипсы обычно без мониторов

**Comment by DmitryHetman** [comment]
Что там на арме то?
Игра мелкая, должно быстро соьратся
