### ISSUE TITLE
Migration to pdcurses

### ISSUE THREAD

**Issue by DmitryHetman** [rainautumn/ttytanks#20]
Use pdcurces for static precompiled version, pdcurses  - cross platform curses implementation, much smaller then ncurses.

**Comment by rainautumn** [comment]
Why?

**Comment by DmitryHetman** [comment]
Hui znaet. (Capability with windows (it's cross-platform library)), also much smaller.

**Comment by DmitryHetman** [comment]
Can you create Functional flow block diagram for this game? I trying to simplify the code, but game doesn't works now, I don't understand function 'render_all' and some others.

**Comment by rainautumn** [comment]
Fuck.. I will try it...

**Comment by DmitryHetman** [comment]
Or just add some comments in code.
