### ISSUE TITLE
Обновление картинки

### ISSUE THREAD

**Issue by DmitryHetman** [rainautumn/ttytanks#8]
Надо убрать обновление картинки и заполнять пробелами место за движущимися объектами. Нет необходимости все перерисовывать.

**Comment by rainautumn** [comment]
возможно ты прав, но обычно перерисовывают заново, на случай ресайза окна или ещё чего. На всякий вообщем случай

**Comment by rainautumn** [comment]
надо бы убрать у ботов возможность поворачиватся на месте. т.к. при повороте у рамки он её стирает. + стоит сделать обновление картинки. уменя какой-то флуд выпадает в эмуляторе и игра превращается в трешак

**Comment by DmitryHetman** [comment]
Пробуй обновления, уже никакой перерисовки окончательно нет,  вот повороты на месте не знаю, танк и так на месте крутить не могу, он двигается, в тетрисе я мог крутить танк на месте насколько помню.

**Comment by DmitryHetman** [comment]
Артефакты ингода выпадают, надо поправить это

**Comment by DmitryHetman** [comment]
Я даже не знаю из-за чего это, надо прикрутить дебагер и смотреть, еще надо прикрутить счетчики, будет видно какие функции наиболее использованые, и какие строки кода наиболие используемые.
Еще надо поправить выход из игры, как инициализируется холст так надо и вернуть терминал в нормальный режим перед выходом, пока что только через CTRL+C могу выходить.
Выход из самого боя тоже надо сделать.

**Comment by DmitryHetman** [comment]
Ресайза окна не будет, это не тот случай когда это разумно, пока рабочая версия использует абсолютную систему координат, но потом надо привести в рабочее состояние и ту что относительную использует и выводит бой по центру экрана.
Узнавать размер экрана надо только при запуске игры, сохранить координаты старта отрисовки и передавать их всем функциям.

**Comment by rainautumn** [comment]
ну как знаешь. слушай, а у тебя лиечка есть? асечка там?

**Comment by DmitryHetman** [comment]
Интернет у меня не стабилен в любом случае, надо что-то завести наверно, асечка устарела, xmpp сейчас норм вроде.

**Comment by DmitryHetman** [comment]
Fixed
